In [13]:
from scipy import signal
import numpy as np


In [14]:
#continous transfer function
#using the given attributes: the cutoff freq = 21.4

cutoff_frequency = 21.4
w0 = 2*np.pi*cutoff_frequency   #the used formula: 2*PI*cutoff_frequency
num = w0
den = [1, w0]
lowPass = signal.TransferFunction(num, den)
print(lowPass)


TransferFunctionContinuous(
array([134.46016557]),
array([  1.        , 134.46016557]),
dt: None
)


In [15]:
#discrete transfer functon
dt = 1.0/1000.0
discretelowPass = lowPass.to_discrete(dt, method = "gbt", alpha = 0.5)
print(discretelowPass)


TransferFunctionDiscrete(
array([0.06299493, 0.06299493]),
array([ 1.        , -0.87401014]),
dt: 0.001
)


In [16]:
#difference equation coefficients
b = discretelowPass.num
a = -discretelowPass.den
print("filter coefficients bi: " + str(b))
print("filter coefficients ai: " + str(a[1:]))



filter coefficients bi: [0.06299493 0.06299493]
filter coefficients ai: [0.87401014]
